Repository ysfchn/DynamicComponents-AI2, pull requests merged in 2020-10, with the labels that each got.

#31 Refactor the code base
  build.xml
  src/com/yusufcihan/DynamicComponents/DynamicComponents.java
Labels: status: done, type: code refactor

#28 Fix Invoke block issue
  src/com/yusufcihan/DynamicComponents/DynamicComponents.java
Labels: status: in progress, type: bug

#29 Change the process by which the LastUsedID block works
  src/com/yusufcihan/DynamicComponents/DynamicComponents.java
Labels: status: waiting for reply
